project:
  type: website
  output-dir: docs

website:
  title: "Ader Villar"
  back-to-top-navigation: true
  # announcement: "Sitio web en construcción"
  # body-footer: "Cursos para la **Universidad Pontificia Bolivariana**, sede Montería"
  # body-header: "## Encabezado para cada página"
  bread-crumbs: true  
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Inicio
        icon: "house-door"
      - text: "cursos"
        menu:
          - text: "Modelos Estocásticos"
            href: /cursos/modelos/
          - text: "Diseño de Experimentos"
            href: /cursos/doe/
          - text: "Programación Lineal"
            href: /cursos/pl/          
          - text: "Simulación"
            href: /cursos/simulacion/
      # - href: about.qmd
      #   text: "Sobre este sitio"
      # - href: blog.qmd
      #   text: Blog
  page-footer: 
    right: "Construído con [Quarto](https://quarto.org/){target='_blank'}"
    left: "&copy; 2026, Ader Villar"

format:
  html:
    theme: superhero
    css: "assets/styles.css"
    toc: true
    lang: es



